name: Rust

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repositry
        uses: actions/checkout@v2

      - name: set up rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        run: cargo build --release --verbose

      - name: save artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/release/gh_actions_test_rs
