name: release

on:
  push:
    branches:
      - main

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repositry
        uses: actions/checkout@v4

      - name: setup environment of Rust 
        uses: dtolnay/rust-toolchain@stable

      - name: test
        run: cargo test --verbose

      - name: build
        run: cargo build --release --verbose

      - name: make artifact
        run: tar -cvzf artifact.tar.gz target/release/gh_actions_test_rs  && mkdir output && mv artifact.tar.gz output

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: output/ 

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    permissions:
      contents: write 

    steps:

      - uses: actions/checkout@v4
      - name: dwonload artifact file
        uses: actions/download-artifact@v4
        with:
          name: build
          path: output/ 

      - name: deploy to Github Release
        run: gh release upload v1.0.0 output/artifact.tar.gz --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
